config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  root to: redirect('/tickets')
  resources :tickets, only: %i[index show]

  namespace :api do
    namespace :v1 do
      resources :tickets, only: %i[create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one :excavator, dependent: :destroy
end

app/controllers/api/v1/application_controller.rb
module Api
  module V1
    class ApplicationController < ActionController::API
      private

      def _run_params(params)
        params.to_unsafe_h
      end
    end
  end
end

app/controllers/api/v1/tickets_controller.rb
module Api
  module V1
    class TicketsController < ApplicationController
      def create
        run Tickets::Operations::Create

        if result.success?
          render json: result[:model], include: :excavator, status: :created
        else
          render json: { errors: result['contract.default'].errors.messages }, status: :unprocessable_entity
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    run Tickets::Operations::Index

    @pagy = result[:pagy]
  end

  def show
    run Tickets::Operations::Show

    if result.success?
      @ticket = result[:model]
    else
      redirect_to action: :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TestProject
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    -# = javascript_pack_tag 'application'
  %body
    .container
      = yield

app/views/tickets/_ticket.html.haml
%tr
  %td= ticket.id
  %td= ticket.request_number
  %td= ticket.sequence_number
  %td= ticket.request_type
  %td= l(ticket.response_due_date_time)
  %td= l(ticket.created_at)
  %td= link_to(t('.show'), ticket_path(ticket))

app/views/tickets/index.html.haml
%h1= t('.title')
- if @model.length == 0
  %p.text-center= t('.no_tickets')
- else
  %table#tickets.table.table-striped
    %thead
      %tr
        %th= Ticket.human_attribute_name(:id)
        %th= Ticket.human_attribute_name(:request_number)
        %th= Ticket.human_attribute_name(:sequence_number)
        %th= Ticket.human_attribute_name(:request_type)
        %th= Ticket.human_attribute_name(:response_due_date_time)
        %th= Ticket.human_attribute_name(:created_at)
        %th= t('.actions')
    %tbody
      = render(@model)
  != pagy_bootstrap_nav(@pagy)

app/views/tickets/show.html.haml
:css
  #map {
    height: 500px;
  }

:javascript
  var TicketsMap = (() => {
    const getPolygonBounds = (polygon) => {
      const bounds = new google.maps.LatLngBounds();
      const paths = polygon.getPaths();

      paths.forEach((path) => {
        path.forEach((point) => {
          bounds.extend(point);
        });
      });

      return bounds;
    }

    const init = () => {
      const coords = #{@ticket.polygon_coordinates.to_json};
      const polygon = new google.maps.Polygon({
        paths: coords,
        strokeColor: '#FF0000',
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: '#FF0000',
        fillOpacity: 0.35
      });
      const map = new google.maps.Map(document.getElementById('map'), {
        mapTypeId: 'terrain'
      });

      map.fitBounds(getPolygonBounds(polygon));
      polygon.setMap(map);
    }

    return { init };
  })();

%script(src="https://maps.googleapis.com/maps/api/js?key=#{Rails.application.credentials.google_api_key}&callback=TicketsMap.init" async defer)

%h1= t('.title')
= link_to(t('.index'), tickets_path)
.my-2
  .row
    .col-3= Ticket.human_attribute_name(:id)
    .col-9= @ticket.id
  .row
    .col-3= Ticket.human_attribute_name(:request_number)
    .col-9= @ticket.request_number
  .row
    .col-3= Ticket.human_attribute_name(:sequence_number)
    .col-9= @ticket.sequence_number
  .row
    .col-3= Ticket.human_attribute_name(:request_type)
    .col-9= @ticket.request_type
  .row
    .col-3= Ticket.human_attribute_name(:response_due_date_time)
    .col-9= l(@ticket.response_due_date_time)
  .row
    .col-3= Ticket.human_attribute_name(:primary_service_area_code)
    .col-9= @ticket.primary_service_area_code
  .row
    .col-3= Ticket.human_attribute_name(:additional_service_area_codes)
    .col-9= @ticket.additional_service_area_codes.to_sentence
  .row
    .col-3= Ticket.human_attribute_name(:created_at)
    .col-9= l(@ticket.created_at)

.my-2
  %h4= t('.excavator')
  .row
    .col-3= Excavator.human_attribute_name(:company_name)
    .col-9= @ticket.excavator.company_name
  .row
    .col-3= Excavator.human_attribute_name(:full_address)
    .col-9= @ticket.excavator.full_address
  .row
    .col-3= Excavator.human_attribute_name(:crew_onsite)
    .col-9= @ticket.excavator.crew_onsite
  .row
    .col-3= Excavator.human_attribute_name(:created_at)
    .col-9= l(@ticket.excavator.created_at)

#map(style="height: 100px, width: 100 px")